# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args: ['ci/cloudbuild/gcp-dependencies']
    volumes:
      - path: /root/.m2/repository
        name: m2_cache
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - '_CACHE_BUCKET=${_CACHE_BUCKET}'
      - '_M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY}'
    waitFor: ['-']

  - name: maven:3-jdk-8
    volumes:
      - path: /root/.m2/repository
        name: m2_cache
    args: [
      "mvn",
      "org.apache.maven.plugins:maven-dependency-plugin:3.1.1:go-offline",
      "org.apache.maven.plugins:maven-dependency-plugin:3.1.1:resolve-plugins"
    ]

  - name: maven:3-jdk-8
    volumes:
      - path: /root/.m2/repository
        name: m2_cache
    args: [
      "mvn",
      "--batch-mode",
      "package",
      "-P", "kafka-0.11-1.0.0"
    ]

  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "--cache-from"
      - "us.gcr.io/${PROJECT_ID}/secor:latest"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:${COMMIT_SHA}"
      - "-t"
      - "us.gcr.io/${PROJECT_ID}/secor:latest"
      - "."

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: bash
    args: ['ci/cloudbuild/gcp-save-dependencies']
    volumes:
      - path: /root/.m2/repository
        name: m2_cache
    env:
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - '_CACHE_BUCKET=${_CACHE_BUCKET}'
      - '_M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY}'
 
timeout: 1200s
images:
  - "us.gcr.io/${PROJECT_ID}/secor"
