#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# _CACHE_BUCKET bucket to save data to
# _M2_LOCAL_REPOSITORY (defaults to /usr/share/maven/ref/repository 
# _REPO_NAME  (used for fallback for non-triggered GCP builds)
# _BRANCH_NAME  (used for fallback for non-triggered GCP builds)
#
# Usage as step:
#
#  - name: 'gcr.io/cloud-builders/gsutil'
#    entrypoint: bash
#    args: ['ci/cloudbuild/gcp-save-dependencies']
#    volumes:
#      - path: /root/.m2/repository
#        name: m2_cache
#    env:
#      - 'REPO_NAME=$REPO_NAME'
#      - 'BRANCH_NAME=$BRANCH_NAME'
#      - '_CACHE_BUCKET=${_CACHE_BUCKET}'
#      - '_M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY}'

set -ex

REPO_NAME=${REPO_NAME:-${_REPO_NAME:-unknown}}
BRANCH_NAME=${BRANCH_NAME:-${_BRANCH_NAME:-unknown}}
M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY:-/usr/share/maven/ref/repository}


cd "${M2_LOCAL_REPOSITORY}" || exit 1

tar -cf /tmp/new_m2.tar .
gsutil cp /tmp/new_m2.tar "gs://${_CACHE_BUCKET}/${REPO_NAME}/${BRANCH_NAME}/m2.tar"
