#!/usr/bin/env bash
# _CACHE_BUCKET bucket to save data to
# _M2_LOCAL_REPOSITORY (defaults to /usr/share/maven/ref/repository 
# _REPO_NAME  (used for fallback for non-triggered GCP builds)
# _BRANCH_NAME  (used for fallback for non-triggered GCP builds)
#
# Usage as a step:
#
#  - name: 'gcr.io/cloud-builders/gsutil'
#    entrypoint: bash
#    args: ['ci/cloudbuild/gcp-dependencies']
#    volumes:
#      - path: /root/.m2/repository
#        name: m2_cache
#    env:
#      - 'REPO_NAME=$REPO_NAME'
#      - 'BRANCH_NAME=$BRANCH_NAME'
#      - '_CACHE_BUCKET=${_CACHE_BUCKET}'
#      - '_M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY}'
#    waitFor: ['-']

set -x

REPO_NAME=${REPO_NAME:-${_REPO_NAME:-unknown}}
BRANCH_NAME=${BRANCH_NAME:-${_BRANCH_NAME:-unknown}}
M2_LOCAL_REPOSITORY=${_M2_LOCAL_REPOSITORY:-/usr/share/maven/ref/repository}

gsutil cp -r "gs://${_CACHE_BUCKET}/${REPO_NAME}/${BRANCH_NAME}/m2.tar" /tmp/m2.tar || exit 0

mkdir -p "${M2_LOCAL_REPOSITORY}/"
tar --extract --file /tmp/m2.tar -C "${M2_LOCAL_REPOSITORY}"
