/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.pinterest.secor.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TestEnum implements org.apache.thrift.TEnum {
  SOME_VALUE(0),
  SOME_OTHER_VALUE(1);

  private final int value;

  private TestEnum(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TestEnum findByValue(int value) { 
    switch (value) {
      case 0:
        return SOME_VALUE;
      case 1:
        return SOME_OTHER_VALUE;
      default:
        return null;
    }
  }
}
