name: CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    name: test
    strategy:
      matrix:
        mvn_profiles: [
          'kafka-2.0.0',
          #  'kafka-1.0.0',
          # 'kafka-0.10.2.0', 'kafka-0.8.2.1'
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "setup"
        run: |
          make dependency_tree
          make unit
